# 基础镜像
FROM redis
# author
MAINTAINER iiss

# 挂载目录
VOLUME /home/iiss/redis
# 创建目录
RUN mkdir -p /home/iiss/redis
# 指定路径
WORKDIR /home/iiss/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/iiss/redis/redis.conf
COPY ./conf/redis.conf /usr/local/etc/redis/redis.conf

