// ---Auto Generated by Only4Play ---
package cn.iiss.trade.order.repository;

import cn.iiss.trade.order.OrderBase;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

public interface OrderBaseRepository extends BaseMapper<OrderBase> {
}
