// ---Auto Generated by Only4Play ---
package cn.iiss.trade.face.request;

import cn.iiss.common.core.domain.CodeValue;
import cn.iiss.commons.annotation.FieldDesc;
import cn.iiss.commons.model.Request;
import cn.iiss.trade.face.model.OrderItemModel;
import lombok.Builder;

import java.math.BigDecimal;
import java.util.List;

@Builder
public class OrderBaseCreateRequest implements Request {

    @FieldDesc(
            name = "订单金额"
    )
    private BigDecimal totalAmount;

    @FieldDesc(
            name = "真实金额"
    )
    private BigDecimal realAmount;

    @FieldDesc(
            name = "用户id"
    )
    private Long userId;

    @FieldDesc(
            name = "订单类型、订单类型创建不同的状态机"
    )
    private Integer orderType;

    @FieldDesc(
            name = "订单信息"
    )
    private List<CodeValue> attrs;

    private List<OrderItemModel> orderItemModelList;

    public List<OrderItemModel> getOrderItemModelList() {
        return orderItemModelList;
    }

    public OrderBaseCreateRequest setOrderItemModelList(List<OrderItemModel> orderItemModelList) {
        this.orderItemModelList = orderItemModelList;
        return this;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }


    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public BigDecimal getRealAmount() {
        return realAmount;
    }

    public void setRealAmount(BigDecimal realAmount) {
        this.realAmount = realAmount;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getOrderType() {
        return orderType;
    }

    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    public List<CodeValue> getAttrs() {
        return attrs;
    }

    public void setAttrs(List<CodeValue> attrs) {
        this.attrs = attrs;
    }
}
