# 基础镜像
FROM nginx
# author
MAINTAINER iiss

# 挂载目录
VOLUME /home/iiss/projects/iiss-ui
# 创建目录
RUN mkdir -p /home/iiss/projects/iiss-ui
# 指定路径
WORKDIR /home/iiss/projects/iiss-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/iiss/projects/iiss-ui
