// ---Auto Generated by Only4Play ---
package cn.iiss.trade.orderitem.request;

import cn.iiss.commons.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class OrderItemQueryRequest implements Request {
}
