// ---Auto Generated by Only4Play ---
package cn.iiss.trade.order.request;

import cn.iiss.common.core.domain.CodeValue;
import cn.iiss.commons.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.util.List;

@Schema
public class OrderBaseCreateRequest implements Request {

    @Schema(
            title = "订单金额"
    )
    private BigDecimal totalAmount;

    @Schema(
            title = "真实金额"
    )
    private BigDecimal realAmount;

    @Schema(
            title = "用户id"
    )
    private Long userId;

    @Schema(
            title = "订单类型、订单类型创建不同的状态机"
    )
    private Integer orderType;

    @Schema(
            title = "订单信息"
    )
    private List<CodeValue> attrs;

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }


    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public BigDecimal getRealAmount() {
        return realAmount;
    }

    public void setRealAmount(BigDecimal realAmount) {
        this.realAmount = realAmount;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getOrderType() {
        return orderType;
    }

    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    public List<CodeValue> getAttrs() {
        return attrs;
    }

    public void setAttrs(List<CodeValue> attrs) {
        this.attrs = attrs;
    }
}
